server:
    port: 8090
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
validation:
    client:
        idcard:
            pattern: ^[A-Z]{6}[0-9]{2}$
        riskcalculator:
            url: http://client-enroll-risk-calc-emu:8091/risk
        existence:
            url: http://client-enroll-customer-exist-emu:8092/exist