server:
    port: 8090
validation:
    client:
        idcard:
            pattern: ^[A-Z]{6}[0-9]{2}$
        riskcalculator:
            url: http://localhost:8091/risk
        existence:
            url: http://localhost:8092/exist